### ISSUE TITLE
USB HID crate.

### ISSUE THREAD

**Issue by daehyeok** [windoze/esparrier-idf#4]
Hi windoze. I found this repo from esp-idf-hal. 
Do you have plan to split USB code to independent crate? It seems only workingable rust hid demo.
Also can you help me to use your usb_util??. I tried to run below minimal code. but it crashed. is it required any other init process??

```rust
fn main() -> Result<()> {
    // It is necessary to call this function once. Otherwise some patches to the runtime
    // implemented by esp-idf-sys might not link properly. See https://github.com/esp-rs/esp-idf-template/issues/71
    esp_idf_sys::link_patches();
    // Bind the log crate to the ESP Logging facilities
    esp_idf_svc::log::EspLogger::initialize_default();
    let peripherals = Peripherals::take().unwrap();
    let sysloop = EspSystemEventLoop::take()?;

    let mut hid = reports::HidReport::new();
    hid.init();
    let key_code = keycodes::KeyCode::Key(keycodes::HID_KEY_A);
    loop {
        // Wait...
        info!("Press!");
        let mut  press = reports::HidReportType::KeyPress{key_code};
        hid.send(press);
        std::thread::sleep(std::time::Duration::from_secs(1));

        info!("Release!");
        let mut release = reports::HidReportType::KeyRelease{key_code};
        hid.send(release);
        std::thread::sleep(std::time::Duration::from_secs(1));
    }
}
```

**Comment by windoze** [comment]
I must admit that the USB code is a bit messy. The source code is taken from an old version of `esp-tinyusb` component which I randomly searched and found from the internet, because the new/current version doesn't work under ESP-IDF 4, and ESP-IDF 5 doesn't include TinyUSB and I cannot make ESP-IDF 5 work with multiple extra components.

Basically the `usb_util` part is just a thin wrapper around TinyUSB, you need 2 things before you can use it in your code:
1. Include this component in your project by including the directory and adding following lines into `Cargo.toml`:
```
[[package.metadata.esp-idf-sys.extra_components]]
component_dirs = ["usb_util"]
```
2. It does require the `usb_util_init` to be called before using any USB functions, this function is defined at https://github.com/windoze/esparrier-idf/blob/00936dcd04b811b34fb887c021020f1924450933/usb_util/usb_util.c#LL179C6-L179C19
You can see it's got called in `UsbHidActuator::connect` through `HidReport::init` function. I delayed the USB initialization because on M5Atom S3 there is no separate USB port for JTAG, once you start using the USB port, the debugging/monitoring/logging function is gone. So I postpone the initialization for as long as possible, even forever if I'm debugging other parts not related to USB.

**Comment by windoze** [comment]
One more thing, the `usb_util` is not a complete and generic USB HID implementation, the HID report descriptors are hard-coded to contain 3 devices:

* A standard HID keyboard.
* An absolute mode HID mouse, I use it because of Barrier related issues, you can use a standard relative mode mouse instead if you needn't know the current mouse position on the screen.
* A HID consumer control device, to adjust volume, play/pause media playing, etc.

You must modify the source code if you want to make any changes to these predefined HID devices.

I still don't have time to design a generic interface over the USB function, that's why I haven't split the USB functions into a separate crate.

**Comment by daehyeok** [comment]
Thanks for reply!. it's working after build/flash with release mode.
I'm trying to build keyboard. so your implementation will be enough.  

Really appreciate again!

**Comment by windoze** [comment]
It may not be a very good idea to build a keyboard with ESP32, as the bluetooth power consumption is significantly higher than the nRF series, and the WiFi function is rarely needed by a real keyboard.

Of course, this is not an issue if the keyboard is powered by USB.

**Comment by daehyeok** [comment]
Yes. i regret that. I don't want to use BLE, it will be wired keyboard. 
 I'm newbie on both of embedded and Rust. So i decided to build EC keyboard for fun and learn RUST. 
 I couldn't find any good size and cheap module. RP2040 is too bulky(official pico board) or expensive. nRF also nearly double price of esp32. and i'm not ready yet to jump into chip soldering. esp32-s3-wroom-1u looks have a good size(although i don't interesting in BLE) with bunch of ADC channel. i just didn't know ESP32's rust eco system is still in premature status.(ESP-HAL's usb create also broken now. https://github.com/esp-rs/esp-hal/issues/495).

**Comment by windoze** [comment]
`esp-hal` is for baremetal development, which is far from mature at the moment. On the other hand `esp-idf-*` crates are based on ESP-IDF, with type-safe wrappers in Rust, so I assume it's much closer to production-ready.

The only problem is that the Rust wrapper itself still has many issues/bugs and missing features, you may need to use C in many places (just like this very project), but the good side is that you can utilize many existing C codes/libs, even the Arduino framework, you can take a look at [esp-idf-template](https://github.com/esp-rs/esp-idf-template) for more info.

**Comment by daehyeok** [comment]
Bare-metal and no_std environment will not a problem on my project. It was my first target because there are many other keyboard project  exists which i can use as a reference.(Mostly  RP2040, nrf of STM) . I don't want to struggle with C on my free time :(. Hopefully it's working well or i will redesign PCB with other MCU.
 
 Thanks for your advise :+1:

**Comment by windoze** [comment]
Sure, Rust seems to be much more promising and less complicated than C to develop apps on MCU.

Since your question is resolved, I'm closing this issue. Feel free to open new one if you have any other questions.
